"""JAX + Optax primitives for zero-gradient evolutionary optimization."""

from ._bin_updates import (
    apply_bin_updates,
    apply_bin_updates_jit,
    bin_update_threshold,
    threshold_tree_for_manifest,
)
from ._cluster import ClusterZeroGrad, ZeroGradNode
from ._distributed import (
    CalibrationResult,
    DeviceShard,
    DistributedZeroGrad,
    ReplicatedDistributedZeroGrad,
    ShardResult,
    compute_partition_sizes,
)
from ._fault_tolerant import FaultTolerantCluster, NodeStatus
from ._fitness import shape_antithetical_loss, shape_centered_loss, validate_losses
from ._fused_lut import fused_linear_lut, int_linear_lut_fused
from ._fused_ternary import (
    fused_ternary_lut,
    packed_ternary_lut_fused,
    ternary_lut_reference,
)
from ._integer import (
    egg_clip_cast,
    egg_init_matrix,
    egg_requantize,
    float_to_egg_i8,
    float_to_int,
    int_avg_pool2d,
    int_conv2d,
    int_conv2d_flat,
    int_matmul,
    pack_ternary,
    unpack_ternary,
)
from ._keys import candidate_key, group_key, step_key
from ._manifest import (
    Manifest,
    ManifestEntry,
    ParameterLayout,
    ParameterPath,
    ParameterTree,
)
from ._nnx import (
    IntAffine,
    IntConv,
    IntEmbedding,
    IntLinear,
    IntLinearLUT,
    IntLUT,
    TernaryLinear,
    TernaryLinearLUT,
    ZeroGradSlot,
    ZgConv,
    ZgEmbed,
    ZgIntConv,
    ZgIntEmbedding,
    ZgIntLinear,
    ZgIntLUT,
    ZgLayerNorm,
    ZgLinear,
    ZgTable,
    ZgTernaryIntLinear,
    ZgTernaryLinear,
    ZgVector,
    apply_surgery,
    collect_int_bits_by_path,
    mark_table,
    mark_ternary,
)
from ._optimizer import ModelLossFn, StepMetrics, ZeroGrad, ZeroGradState
from ._snn import (
    Leaky,
    Spiking,
    encode_poisson,
    encode_rate,
    spike_count_logits,
)

__all__ = [
    "CalibrationResult",
    "ClusterZeroGrad",
    "DeviceShard",
    "DistributedZeroGrad",
    "FaultTolerantCluster",
    "IntAffine",
    "IntConv",
    "IntEmbedding",
    "IntLUT",
    "IntLinear",
    "IntLinearLUT",
    "Manifest",
    "ManifestEntry",
    "ModelLossFn",
    "NodeStatus",
    "ParameterLayout",
    "ParameterPath",
    "ParameterTree",
    "ReplicatedDistributedZeroGrad",
    "ShardResult",
    "StepMetrics",
    "TernaryLinear",
    "TernaryLinearLUT",
    "Leaky",
    "Spiking",
    "ZeroGrad",
    "ZeroGradNode",
    "ZeroGradSlot",
    "ZeroGradState",
    "ZgConv",
    "ZgEmbed",
    "ZgIntConv",
    "ZgIntEmbedding",
    "ZgIntLUT",
    "ZgIntLinear",
    "ZgLayerNorm",
    "ZgLinear",
    "ZgTable",
    "ZgTernaryLinear",
    "ZgVector",
    "apply_bin_updates",
    "apply_bin_updates_jit",
    "apply_surgery",
    "bin_update_threshold",
    "candidate_key",
    "collect_int_bits_by_path",
    "compute_partition_sizes",
    "egg_clip_cast",
    "encode_poisson",
    "encode_rate",
    "egg_init_matrix",
    "egg_requantize",
    "float_to_egg_i8",
    "float_to_int",
    "fused_linear_lut",
    "fused_ternary_lut",
    "group_key",
    "int_avg_pool2d",
    "int_conv2d",
    "int_conv2d_flat",
    "int_linear_lut_fused",
    "int_matmul",
    "mark_table",
    "mark_ternary",
    "pack_ternary",
    "packed_ternary_lut_fused",
    "shape_antithetical_loss",
    "spike_count_logits",
    "shape_centered_loss",
    "step_key",
    "ternary_lut_reference",
    "threshold_tree_for_manifest",
    "unpack_ternary",
    "validate_losses",
]
