"""JAX + Optax primitives for zero-gradient evolutionary optimization."""

from ._cluster import ClusterZeroGrad, ZeroGradNode
from ._distributed import (
    CalibrationResult,
    DeviceShard,
    DistributedZeroGrad,
    ReplicatedDistributedZeroGrad,
    ShardResult,
    compute_partition_sizes,
)
from ._fault_tolerant import FaultTolerantCluster, NodeStatus
from ._fitness import shape_centered_loss, validate_losses
from ._keys import candidate_key, group_key, step_key
from ._manifest import Manifest, ManifestEntry, ParameterLayout, ParameterPath, ParameterTree
from ._integer import (
    egg_clip_cast,
    egg_init_matrix,
    egg_requantize,
    float_to_egg_i8,
    float_to_int,
    int_avg_pool2d,
    int_conv2d,
    int_conv2d_flat,
    int_matmul,
)
from ._nnx import (
    IntAffine,
    IntConv,
    IntEmbedding,
    IntLinear,
    IntLinearLUT,
    IntLUT,
    TernaryLinear,
    ZgConv,
    ZgEmbed,
    ZgIntConv,
    ZgIntEmbedding,
    ZgIntLinear,
    ZgIntLUT,
    ZgLayerNorm,
    ZgLinear,
    ZgTable,
    ZgTernaryLinear,
    ZgVector,
    ZeroGradSlot,
    apply_surgery,
    mark_table,
)
from ._optimizer import ModelLossFn, StepMetrics, ZeroGrad, ZeroGradState
from ._eggroll_h import (
    apply_bin_updates,
    apply_bin_updates_jit,
    bin_update_threshold,
    shape_antithetical_loss,
    threshold_tree_for_manifest,
)

__all__ = [
    "CalibrationResult",
    "ClusterZeroGrad",
    "DeviceShard",
    "DistributedZeroGrad",
    "FaultTolerantCluster",
    "IntAffine",
    "IntConv",
    "IntEmbedding",
    "IntLinear",
    "IntLinearLUT",
    "IntLUT",
    "Manifest",
    "ManifestEntry",
    "ModelLossFn",
    "NodeStatus",
    "ParameterLayout",
    "ReplicatedDistributedZeroGrad",
    "ParameterPath",
    "ParameterTree",
    "ShardResult",
    "StepMetrics",
    "TernaryLinear",
    "ZgConv",
    "ZgEmbed",
    "ZgIntConv",
    "ZgIntEmbedding",
    "ZgIntLinear",
    "ZgIntLUT",
    "ZgLayerNorm",
    "ZgLinear",
    "ZgTable",
    "ZgTernaryLinear",
    "ZgVector",
    "ZeroGrad",
    "ZeroGradNode",
    "ZeroGradSlot",
    "ZeroGradState",
    "apply_bin_updates",
    "apply_bin_updates_jit",
    "apply_surgery",
    "bin_update_threshold",
    "threshold_tree_for_manifest",
    "candidate_key",
    "compute_partition_sizes",
    "egg_clip_cast",
    "egg_init_matrix",
    "egg_requantize",
    "float_to_egg_i8",
    "float_to_int",
    "group_key",
    "int_avg_pool2d",
    "int_conv2d",
    "int_conv2d_flat",
    "int_matmul",
    "mark_table",
    "shape_antithetical_loss",
    "shape_centered_loss",
    "step_key",
    "validate_losses",
]
